version: "3"

services:
  front:
    build:
      dockerfile: docker/front/Dockerfile
      context: .

  api:
    build:
      dockerfile: docker/api/Dockerfile
      context: .
    environment:
      SECRETS_JSON: secrets/secrets.json
    ports:
      - "12300:12300"

  db:
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"

